# Generated by Django 4.1.4 on 2023-02-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='specifications',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phone',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
