# Generated by Django 4.1.4 on 2023-02-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_phone_specifications_alter_phone_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='count',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
